### ISSUE TITLE
Hard-coded service selector

### ISSUE THREAD

**Issue by mgoodness** [jetstack/kube-lego#78] opened 2017-01-11 22:43 UTC
The auto-created kube-lego service has its selector [hard-coded](https://github.com/jetstack/kube-lego/blob/master/pkg/service/service.go#L105) to `app: kube-lego`. If I start a kube-lego pod doesn't match that label (e.g. `app: foo`), the service will not have any endpoints.

I know I can create a service with its selector set to `app: foo` and pass its name into the pod as `LEGO_SERVICE_NAME_NGINX`. However, kube-lego will then [update](https://github.com/jetstack/kube-lego/blob/master/pkg/provider/nginx/nginx.go#L62) the service and set its selector (incorrectly) to `app: kube-lego`.

Can there be a way to either provide the correct selectors or instruct kube-lego not to change the provided service? I think I favor the latter. Everyone uses labels differently, so flexibility is needed. I'm willing to submit a PR.

**Comment by simonswine** [comment] 2017-02-06 19:00
Sorry for the long wait, this is a bug and should be fixed. Happy to get a PR

**Comment by ankon** [comment] 2017-03-20 12:52
(For tracking: this is a duplicate of #25 )

**Comment by jsulinski** [comment] 2017-06-06 19:01
Is there any reason to leave both versions of this issue open? 

Dupe comment here, asking about an update on stauts: https://github.com/jetstack/kube-lego/issues/25#issuecomment-306584719

**Comment by ant31** [comment] 2017-07-20 14:30
Does it take more than adding a env var?

**Closed** 2017-09-25 19:50 UTC
Labels: priority/P1
