### ISSUE TITLE
Does not work with the nginx-ingress-controller:0.9.0-betaX version

### ISSUE THREAD

**Issue by guizmaii** [jetstack/kube-lego#252] opened 2017-09-01 10:13 UTC
Hello,

Just to report that kube-lego seems not to work with the `0.9.0-betaX` version of the Nginx Ingress.
The default certificate of the Nginx Ingress is never replaced by the fetched LetsEncrypt one.

![capture d ecran 2017-09-01 12 11 52](https://user-images.githubusercontent.com/1193670/29965673-db82327a-8f0e-11e7-9810-59216a167c13.png)

**Comment by cguethle** [comment] 2017-09-01 13:10
There have been ongoing issues with 0.9.0-beta with respect to certificates from kube-lego. Primarily, the nginx ingress requires a restart to load the newly secured cert. Have you tried restarting your ingress containers? What beta version are you working with? There have been numerous attempts to address it over the course of the beta version. Not sure if 12 is working yet or not.

**Comment by guizmaii** [comment] 2017-09-01 14:06
I tested with the 0.9.0-beta12: not working.

`Have you tried restarting your ingress containers?` => No. 
Nginx already reload its configuration automatically (maybe because kube-lego ask, I don't know), no ? 
It's what I can observe with the 0.8.3 version of Nginx Ingress.

**Comment by aledbf** [comment] 2017-09-01 14:09
Where are you running.and which kubernetes version you are using?

**Comment by cguethle** [comment] 2017-09-01 14:10
> Nginx already reload its configuration automatically (maybe because kube-lego ask, I don't know), no ?
I believe this is where the failure is/has been.

**Comment by guizmaii** [comment] 2017-09-01 14:36
> Where are you running.and which kubernetes version you are using?

GKE with K8s 1.7.3

**Comment by munnerz** [comment] 2017-09-01 17:14
kube-lego itself does not 'tell' the ingress controller to reload it's config. It's the responsibility of nginx-ingress to watch the secrets referenced in Ingress resources for changes, and upon change, reload config.

It seems there was a regression somewhere in the nginx-ingress 0.9.0-betaX release cycle, which as far as I was aware was fixed, however perhaps not.

The corresponding issue on the nginx-ingress repository is here: https://github.com/kubernetes/ingress/issues/1263

I'd suggest adding a comment to that Issue, and reopening it if it is re-occurring with the latest beta. I'm going to close this issue as it's not a bug on the kube-lego side of things, but thanks for reporting it anyway! 😄

**Closed by munnerz** 2017-09-01 17:14 UTC
