### ISSUE TITLE
Disable nginx provider entirely

### ISSUE THREAD

**Issue by apognu** [jetstack/kube-lego#192] opened 2017-05-26 15:59 UTC
Hi,

I'm running Kubernetes on GCE, and since I'm not using nginx at all, I thought specifying ```LEGO_SUPPORTED_INGRESS_CLASS=gce``` and ```LEGO_DEFAULT_INGRESS_CLASS=gce``` would disable any nginx logic entirely.

Apparently, that's not the case, I still get messages about RBAC not letting ```get services kube-lego-nginx``` go through or ```do not delete service '/' as it has no kubernetes.io/kube-lego-managed annotation" context=provider provider=nginx```.

That's not a real problem, but it does clutter the logs (some of those message appear as ```error```s.

Is this the proper way to disable nginx? Is it a bug?

Thanks.

**Comment by munnerz** [comment] 2017-07-05 12:58
This comes about because right now there's no conditional logic to actually not call the providers `New` function if the provider is not 'supported' (see: https://github.com/jetstack/kube-lego/blob/master/pkg/kubelego/kubelego.go#L110)

There's a number of PRs right now that touch this bit of logic (eg. https://github.com/jetstack/kube-lego/pull/194 and https://github.com/jetstack/kube-lego/pull/202).

Once one of these is merged, it'd be great if you can test this again!

**Comment by munnerz** [comment] 2017-07-05 13:48
This should now be fixed as #202 has been merged - can you confirm that the messages no longer appear when using the :canary release? Please re-open if the issue is not resolved!

**Closed by munnerz** 2017-07-05 13:48 UTC
Labels: bug
