### ISSUE TITLE
[nginx] Ingress constantly drops and recreates static ip

### ISSUE THREAD

**Issue by jackzampolin** [jetstack/kube-lego#47] opened 2016-10-18 00:54 UTC
```
$ kubectl describe ing proding --namespace prodenv
Name:			proding
Namespace:		prodenv
Address:		
Default backend:	default-http-backend:80 (10.48.2.7:8080)
TLS:
  proding-tls terminates www.{foo}.com,{foo}.com,www.{foo}.design,{foo}.design
Rules:
  Host			Path	Backends
  ----			----	--------
  www.{foo}.com	
    			/ 	jackserver:80 (<none>)
  {foo}.com	
    			/ 	jackserver:80 (<none>)
  www.{foo}.design	
    			/ 	pylonserver:80 (<none>)
  {foo}.design		
    			/ 	pylonserver:80 (<none>)
Annotations:
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason	Message
  ---------	--------	-----	----				-------------	--------	------	-------
  15m		15m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  15m		15m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  15m		15m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  14m		14m		1	{nginx-ingress-controller }			Normal		DELETE	ip: 104.196.29.121
  14m		14m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  14m		14m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  14m		14m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  9m		9m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  9m		9m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  9m		9m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  8m		8m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  8m		8m		1	{nginx-ingress-controller }			Normal		DELETE	ip: 104.196.29.121
  8m		8m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  8m		8m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  2m		2m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  2m		2m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  2m		2m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  2m		2m		1	{nginx-ingress-controller }			Normal		CREATE	prodenv/proding
  2m		2m		1	{nginx-ingress-controller }			Normal		CREATE	ip: 104.196.29.121
  2m		2m		1	{nginx-ingress-controller }			Normal		UPDATE	prodenv/proding
  1m		1m		1	{nginx-ingress-controller }			Normal		DELETE	ip: 104.196.29.121
```
[Gist with configs](https://gist.github.com/jackzampolin/4da3a5fbdecacf682f951f3b9bf3263f)

The backends were reachable initially but then the wonkyness started.

I am happy to provide any debugging information.

**Comment by jackzampolin** [comment] 2016-10-18 00:55
@johnparn

**Comment by jackzampolin** [comment] 2016-10-18 16:27
After some more looking, I've found that the Ingress is not associating with the LB which is causing the Ingress to constantly create and delete IPs.

**Comment by jackzampolin** [comment] 2016-10-18 18:36
@simonswine Any thoughts on this? Also in the `nginx` example there are no `kube-lego-service.yml` or pre-tls `ingress` examples.

**Comment by simonswine** [comment] 2016-10-18 19:10
Looks like a nginx ingress problem (my guess is it's pods are constantly restarting).

I think the problem is in this line

```
- --nginx-configmap=nginx-ingress/nginx
```

It should be like that:

```
 - --nginx-configmap=prodenv/nginx
```


But the log of the nginx pods will tell you more

**Comment by jackzampolin** [comment] 2016-10-18 19:17
@simonswine Turns out the port in the `50-nginx-deployment.yaml` is wrong. Need to change port from `10249` to `10254` and version from `0.8.2` to `0.8.3`

**Comment by simonswine** [comment] 2016-10-18 21:46
Yeah I had that problem as well, but if you stick to the example with 0.8.2 and 10249, it should have worked...

Just closing this let me know feel free to reopen if needed

**Closed by simonswine** 2016-10-18 21:46 UTC
Labels: question

**Comment by jackzampolin** [comment] 2016-10-18 22:00
Close it! Thanks for writing awesome software @simonswine! I'll go ahead and close my other issue out as well!
