### ISSUE TITLE
wrong http-health-check in GCE with pod with custom readinessProbe

### ISSUE THREAD

**Issue by mjumelet** [jetstack/kube-lego#68] opened 2016-12-29 16:22 UTC
I followed the GCE example step-by-step and got the echo service working correctly.

Now i'm trying to get it working with one of my own services as a backend, it looks like it is caused by a wrong health check being generated for the "kube-lego-gce" service. The most likely cause is probably my custom service has a different health check url.

This is what I get after the GCE echoserver demo as backend services
"k8s-be-30374--1042ee2c178ccecf":"HEALTHY" --> kube-lego-gce
"k8s-be-30383--1042ee2c178ccecf":"HEALTHY" --> echoserver
"k8s-be-31710--1042ee2c178ccecf":"HEALTHY" --> default-http-backend

with the following health checks:
k8s-be-30374--xxxx 30374 / --> kube-lego-gce
k8s-be-30383--xxxx 30383 / --> echoserver
k8s-be-31710--xxxx 31710 /healthz --> default-http-backend

With my own backend service (with a different readinessProbe defined for the pod) i get
"k8s-be-30184--xxxx":"HEALTHY" -->my-own-app-service
"k8s-be-31710--xxxx":"HEALTHY" --> default-http-backend
"k8s-be-32502--xxxx":"**UNHEALTHY** --> kube-lego-gce

k8s-be-30184--xxxx 30184 /health --> my-own-app-service
k8s-be-31710--xxxx 31710 /healthz --> default-http-backend
k8s-be-32502--xxxx 32502 /health --> kube-lego-gce

As you can see the health check for "kube-lego-gce" is different ("/" versus "/health"), looking at the acme.go source code I can see it has a mapping for "/" and "/healthz" and not "/health", it looks like it should be "/healthz" which even the example source does not generate in my case.

Any idea how i can force the health check for kube-lego-service to be set to a certain endpoint?

**Comment by mjumelet** [comment] 2016-12-29 19:27
I changed the readinessProbe of the my-own-app pod, it changed the health url of both health-checks url (kube-lego-gce & my-own-app-service) to the updated url, this is of course incorrect, the health check url of kube-lego-gce should be /healthz

**Comment by jniemin** [comment] 2017-01-16 15:55
I was just deploying Jenkins to Kubernetes and using kube-lego to retrieve certificates for it. As jenkins is defining readinessProbe like
```readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
```

Then kube-lego health check requestPath was created to point /login as well

```checkIntervalSec: 10
creationTimestamp: '2017-01-16T07:40:44.357-08:00'
description: kubernetes L7 health check from readiness probe.
healthyThreshold: 2
host: ''
id: 'XXXXX'
kind: compute#httpHealthCheck
name: k8s-be-XXX
port: 31919
requestPath: /login
selfLink: https://www.googleapis.com/compute/v1/projects/myprojectid/global/httpHealthChecks/k8s-be-XXXX
timeoutSec: 5
unhealthyThreshold: 5
```

I fixed with manually patching it to point to /healthz but definitely there is something wrong how kube-lego backend is created

**Comment by amochtar** [comment] 2017-02-25 17:06
I ran into the exact same thing today. The health check for kube-lego was configured as `/v0/healthz` (which is my pod's custom health check endpoint), rather than `/healthz`.

Any updates on this?

**Comment by bbzg** [comment] 2017-04-03 21:03
Yes I got this too, using jenkins with readinessProbe set to /login, and guess what - kube-lego readiness probe also set to /login

Along with a number of other issues as well....

**Comment by bvoss** [comment] 2017-05-24 14:51
I also ran into this.

The root cause, I think, is missing "selector" attribute on the kube-lego-gce service. If its there the default health check of "/" is used. If not the health check of the backend is used. This is not related to kube-lego. You can reproduce it with any service like in the attached yaml. [ingress-test.txt](https://github.com/jetstack/kube-lego/files/1025952/ingress-test.txt)

I see three options to solve this:

1.  add a selector pointing to nowhere to the kube-lego-gce service (don't know the implications)
2. open a issue for the kubernetes ingress provider to fall back to default "/" health check without a selector (don't know how long this will take)
3. let kube-lego response to all requests (except /.well-known/acme-challenge) with 200 OK (just a quikfix but the way I'll take for now)

What do you think?

**Comment by yudilevi** [comment] 2017-07-20 16:31
It's not clear to me whether there's anything I can do to fix it in our deployment - we're on GKE and using the default /healthz path.
kube-lego-gce still picks up a path from a different service.
Is there any workaround?

**Comment by michaelbannister** [comment] 2017-09-05 10:46
I've also just hit this problem! Still pretty new to kubernetes & gcloud so not ready to dive in suggesting fixes or submitting pull requests... is there any workaround other than changing all my other endpoints to health-check on /healthz ?!

**Comment by michaelbannister** [comment] 2017-09-05 15:21
Is this perhaps caused by this issue with the GCE ingress controller? https://github.com/kubernetes/ingress/issues/720

**Comment by bvoss** [comment] 2017-09-06 05:12
@michaelbannister As fare as I know this is the only workaround.
This wasn't acceptable for me and the only reason I did my very small fork. The only change is to respond to all Urls except /.well-known/acme-challenge with 200 OK (see me earlier comment)

**Comment by yudilevi** [comment] 2017-09-06 09:43
It's still not clear to me how to workaround this issue, especially since some of the pods I have have their own built in health check endpoint that I have no control over.
Can someone from the devs comment on that?

**Comment by bvoss** [comment] 2017-09-06 10:28
@yudilevi tI don't know a workaround if you have pods with other health endpoints.
That was the only reason for my fork.

**Comment by yudilevi** [comment] 2017-09-06 11:18
@bvoss gotcha - thanks. Hopefully the devs can share more light on it.

**Comment by munnerz** [comment] 2017-09-06 11:43
So from my understanding, this is a limitation of the Ingress API/GCLB ingress implementation.

We use a selectorless service to direct traffic to kube-lego in order to solve challenges. It *has* to be selectorless as we manually managed endpoint resources for this service, in order to support cross-namespace use of kube-lego.

I need to investigate the issue properly to propose a solution, however I'm interested in trying out/working with @bvoss's suggestion (https://github.com/gianrubio/kube-lego/commit/873f22454b3903545d82fa56e9309081df64d9d5).

As I've not had a chance to properly dig into this problem, I don't have an immediate solution to suggest. I would be interested to hear if these same issues are resolved with using [cert-manager](https://github.com/jetstack-experimental/cert-manager), as that solves challenges between namespaces by creating Jobs in the target namespace that solve each challenge. This means we no longer user a selectorless service when on GCE! 😄

**Comment by DocX** [comment] 2017-10-30 11:42
Hi, as setting up health-check address on non-selector services is out of control kube-lego, I found another workaround.

If I can create `kube-lego-gce` service manually with selector to kube-lego pod, and then run kube-lego manually in all of my namespaces, it should work.

Only drawback is running multiple kube-lego pods, but given it is really small, I don't see massive issue with that.

But there seems to be a bug in kube-lego, that despite the service normally has "kube-lego-managed" annotation, this annotation is being in fact ignored and kube-lego always replaces the service to endpoint one, no matter what.

So I made fix that will allow this workaround in https://github.com/jetstack/kube-lego/pull/267

**Comment by ramzimaalej** [comment] 2017-11-30 06:31
is there a plan to fix this issue?

**Comment by tjma2001** [comment] 2018-01-23 00:23
I guess not. Its been open for over a year.

**Comment by simonswine** [comment] 2018-01-23 09:42
Wrong guess @tjma2001. 

The workaround for repsonding to `/` with 200 is in place for quite a while, the latest canary tag implements the kube-lego maintained annoation. 

This is what kube-lego can fix. For GCE multi-namespace support it needs selector-less services. These don't respect the readiness probe on the referenced pods

**Closed by simonswine** 2018-01-23 09:42 UTC
