### ISSUE TITLE
Works, but stuck in loop

### ISSUE THREAD

**Issue by rolftimmermans** [jetstack/kube-lego#137] opened 2017-04-06 10:40 UTC
Certificates are being provisioned correctly, but then `kube-lego` seems to be stuck in a loop every second or so (rather than the expected 8 hours for a validity check).

The following are the last lines from the log file:

```
time="2017-04-06T10:37:04Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.0.10 provider=gce 
time="2017-04-06T10:37:05Z" level=debug msg=reset context=provider provider=nginx 
time="2017-04-06T10:37:05Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-04-06T10:37:05Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-04-06T10:37:05Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-04-06T10:37:05Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-07-05 09:32:00 +0000 UTC name=api namespace=default 
time="2017-04-06T10:37:05Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=default 
time="2017-04-06T10:37:05Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-04-06T10:37:05Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-04-06T10:37:05Z" level=debug msg=reset context=provider provider=gce 
time="2017-04-06T10:37:05Z" level=debug msg="UPDATE ingress/default/api" context=kubelego 
time="2017-04-06T10:37:05Z" level=debug msg=finialize context=provider provider=gce 
time="2017-04-06T10:37:05Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.0.10 provider=gce 
time="2017-04-06T10:37:06Z" level=debug msg=reset context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-04-06T10:37:06Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-07-05 09:32:00 +0000 UTC name=api namespace=default 
time="2017-04-06T10:37:06Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=default 
time="2017-04-06T10:37:06Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-04-06T10:37:06Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-04-06T10:37:06Z" level=debug msg=reset context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-04-06T10:37:06Z" level=debug msg=reset context=provider provider=gce 
time="2017-04-06T10:37:06Z" level=debug msg="UPDATE ingress/default/api" context=kubelego 
time="2017-04-06T10:37:06Z" level=debug msg=finialize context=provider provider=gce 
time="2017-04-06T10:37:07Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.0.10 provider=gce 
time="2017-04-06T10:37:07Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-04-06T10:37:07Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-07-05 09:32:00 +0000 UTC name=api namespace=default 
time="2017-04-06T10:37:07Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=default 
time="2017-04-06T10:37:07Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-04-06T10:37:07Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-04-06T10:37:07Z" level=debug msg=reset context=provider provider=gce 
time="2017-04-06T10:37:07Z" level=debug msg=finialize context=provider provider=gce 
time="2017-04-06T10:37:07Z" level=debug msg="UPDATE ingress/default/api" context=kubelego 
time="2017-04-06T10:37:08Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.0.10 provider=gce 
time="2017-04-06T10:37:08Z" level=debug msg=reset context=provider provider=nginx 
time="2017-04-06T10:37:08Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-04-06T10:37:08Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-04-06T10:37:08Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-04-06T10:37:09Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-07-05 09:32:00 +0000 UTC name=api namespace=default 
time="2017-04-06T10:37:09Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=default 
time="2017-04-06T10:37:09Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-04-06T10:37:09Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-04-06T10:37:09Z" level=debug msg=reset context=provider provider=gce 
time="2017-04-06T10:37:09Z" level=debug msg=finialize context=provider provider=gce 
time="2017-04-06T10:37:09Z" level=debug msg="UPDATE ingress/default/api" context=kubelego 
time="2017-04-06T10:37:09Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip=10.0.0.10 provider=gce 
```

This seems to be repeated infinitely every second or so.

`LEGO_CHECK_INTERVAL` is set to `8h` though

The image I'm running is `jetstack/kube-lego:0.1.3`.

**Comment by yudilevi** [comment] 2017-04-21 00:48
Happens to me as well on one of my clusters, running on GKE using the same version - 0.1.3.

**Comment by tsloughter** [comment] 2017-04-27 18:40
I'm confused and stuck with this loop as well. I have other deployments working fine in other clusters but now the GKE clusters I create and deploy kube-lego (0.1.3 chart) don't do anything after getting the certificate and creating the secret. I just keep seeing this log that seems related:

```
time="2017-04-27T18:29:17Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
```

**Comment by SimonTernoir** [comment] 2017-05-13 10:17
I've got the same issue :/

**Comment by gianrubio** [comment] 2017-05-15 08:21
@rolftimmermans, @yudilevi , @SimonTernoir  this is not really a bug however kube-lego can be less verbose comparing the changes of the ingress resource.

Just to you understand, kube-lego is `watching` for events of the ingress resources, so when a change is detected it "restart" because the resources was changed.  This part of your log show the `event` comming from k8s api. 

```
time="2017-04-06T10:37:07Z" level=debug msg="UPDATE ingress/default/api" context=kubelego 
```

@tsloughter please upgrade kube-lego to v0.1.4, if the issue still happen please open a new issue.

**Comment by rolftimmermans** [comment] 2017-05-17 13:45
I don't understand – there are no changes being made...? Which is why this behaviour surprises me. I expect `kube-lego` to be relatively silent when everything is configured and only occasionally check for renewal. 

I tried with 0.1.4 but I get a similar result. The following output repeats itself continuously, even though nothing on the cluster changed:

```
time="2017-05-17T13:43:55Z" level=debug msg="setting up svc endpoint" context=provider namespace=staging pod_ip=10.64.37.6 provider=gce 
time="2017-05-17T13:43:55Z" level=info msg="process certificate requests for ingresses" context=kubelego 
time="2017-05-17T13:43:55Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:10:00 +0000 UTC name=api namespace=staging 
time="2017-05-17T13:43:55Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=staging 
time="2017-05-17T13:43:56Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:16:00 +0000 UTC name=site namespace=staging 
time="2017-05-17T13:43:56Z" level=info msg="no cert request needed" context="ingress_tls" name=site namespace=staging 
time="2017-05-17T13:43:56Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-05-17T13:43:56Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-05-17T13:43:56Z" level=info msg="ignoring as has no annotation 'kubernetes.io/tls-acme'" context=ingress name=kube-lego-nginx namespace=service 
time="2017-05-17T13:43:56Z" level=debug msg=reset context=provider provider=gce 
time="2017-05-17T13:43:56Z" level=debug msg=finalize context=provider provider=gce 
time="2017-05-17T13:43:56Z" level=debug msg="UPDATE ingress/staging/site" context=kubelego 
time="2017-05-17T13:43:56Z" level=debug msg="setting up svc endpoint" context=provider namespace=staging pod_ip=10.64.37.6 provider=gce 
time="2017-05-17T13:43:56Z" level=debug msg=reset context=provider provider=nginx 
time="2017-05-17T13:43:56Z" level=debug msg=finalize context=provider provider=nginx 
time="2017-05-17T13:43:57Z" level=info msg="process certificate requests for ingresses" context=kubelego 
time="2017-05-17T13:43:57Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:10:00 +0000 UTC name=api namespace=staging 
time="2017-05-17T13:43:57Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=staging 
time="2017-05-17T13:43:57Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:16:00 +0000 UTC name=site namespace=staging 
time="2017-05-17T13:43:57Z" level=info msg="no cert request needed" context="ingress_tls" name=site namespace=staging 
time="2017-05-17T13:43:57Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-05-17T13:43:57Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-05-17T13:43:57Z" level=info msg="ignoring as has no annotation 'kubernetes.io/tls-acme'" context=ingress name=kube-lego-nginx namespace=service 
time="2017-05-17T13:43:57Z" level=debug msg=reset context=provider provider=gce 
time="2017-05-17T13:43:57Z" level=debug msg=finalize context=provider provider=gce 
time="2017-05-17T13:43:57Z" level=debug msg="UPDATE ingress/staging/site" context=kubelego 
time="2017-05-17T13:43:57Z" level=debug msg="setting up svc endpoint" context=provider namespace=staging pod_ip=10.64.37.6 provider=gce 
time="2017-05-17T13:43:58Z" level=debug msg=reset context=provider provider=nginx 
time="2017-05-17T13:43:58Z" level=debug msg=finalize context=provider provider=nginx 
time="2017-05-17T13:43:58Z" level=info msg="process certificate requests for ingresses" context=kubelego 
time="2017-05-17T13:43:59Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:10:00 +0000 UTC name=api namespace=staging 
time="2017-05-17T13:43:59Z" level=info msg="no cert request needed" context="ingress_tls" name=api namespace=staging 
time="2017-05-17T13:43:59Z" level=info msg="cert expires in 75.9 days, no renewal needed" context="ingress_tls" expire_time=2017-08-01 12:16:00 +0000 UTC name=site namespace=staging 
time="2017-05-17T13:43:59Z" level=info msg="no cert request needed" context="ingress_tls" name=site namespace=staging 
time="2017-05-17T13:43:59Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-05-17T13:43:59Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-05-17T13:43:59Z" level=info msg="ignoring as has no annotation 'kubernetes.io/tls-acme'" context=ingress name=kube-lego-nginx namespace=service 
time="2017-05-17T13:43:59Z" level=debug msg=reset context=provider provider=gce 
t
```

**Comment by Kenblair1226** [comment] 2017-05-24 06:00
Same here. I have 3 clusters on GKE, all running k8s 1.6.2 with kube-lego 0.1.3. 
The 2 old clusters work perfectly fine. Only the one created today has this issue. Upgrade to 0.1.4 doesn't help. The log looks like kube-lego watch process is triggering cert update every second.

**Comment by teelahti** [comment] 2017-05-29 16:48
We got today rate-limited by Google Cloud Engine API because of this. Started after upgrading the cluster to 1.6.2. Also 1.6.4 Kubernetes has same behaviour.

**Comment by munnerz** [comment] 2017-06-02 10:02
So as @gianrubio says, it appears this isn't an issue with Kube-Lego actually *retrieving* the certificates from Letsencrypt every few seconds. It's noticing that there's been some kind of change to the ingress resource fairly regularly (not sure exactly what this change is without further inspection of the clusters affected), and so doing a check of the certificate to ensure it's still valid. It then detects that it is, and finishes. At no point should the Letsencrypt or any other external API be called. Then another update happens and it starts again!

I can't currently tell from the logs whether it is kube-lego performing this update to the ingress after it's run, or another k8s component.

In order to resolve this, we'd ideally need to know what changes are happening to the ingress resource in order to trigger the event. We know that it *is* an update event from the API server due to `time="2017-05-17T13:43:57Z" level=debug msg="UPDATE ingress/staging/site" context=kubelego `. Once we work that out, we can determine (1) whether this is in fact a bug with kube-lego, or if another component is causing needless and constant updates to Ingress resources thus necessarily triggering a check of the certificate. (2) whether we need to change the heuristic kube-lego uses to detect changes to Ingress resources.

@teelahti - do you know what API limit was exhausted here? As far as I know, kube-lego doesn't call out the the google cloud API at all during it's normal working, as it simply creates resources (eg. services, ingress resources) in order to make *other* components perform updates to external APIs.

**Comment by rolftimmermans** [comment] 2017-06-02 10:29
If anyone can point me in the right direction I'd be happy to try and figure out what kind of update is happening so often on our cluster.

**Comment by teelahti** [comment] 2017-06-02 10:49
@munnerz : Never found out which API method was the most called as Google Clouds API manager does not expose that too well. All I know that I saw the frequent 1 per second updates on all our Kube-lego instances (on logs), and when I dropped Kube-lego out of the cluster total API calls dropped from 15-20 per second to one per second on a cluster with 2 kube-lego instances and 4 certificates. For us this started when upgrading to 1.6.2, and reproduced on all clusters.

Google Cloud gives 2000 API calls per user per 100 seconds, thus we hit the limit and our Kubernetes account was unusable and couldn't e.g. create ingress resources anymore.  

I'm pretty sure I can cause the situation again by re-deploying kube-lego. What kubectl call would give information that helps? `kubectl describe ingress my-ingress` maybe?

**Comment by rolftimmermans** [comment] 2017-06-02 12:54
So I modified https://github.com/softonic/kubewatch to also list updates.

Here's a diff of the update that happens every second or so:

```
--- untitled
+++ (clipboard)
@@ -4,7 +4,7 @@
     "namespace": "staging",
     "selfLink": "/apis/extensions/v1beta1/namespaces/staging/ingresses/site",
     "uid": "a62cf087-3001-11e7-b091-42010a840253",
-    "resourceVersion": "8453829",
+    "resourceVersion": "8453828",
     "generation": 38,
     "creationTimestamp": "2017-05-03T13:08:49Z",
     "labels": {
```

So it still doesn't tell me why the update is happening, but if only the version changes it shouldn't really trigger an update, should it?

**Comment by rolftimmermans** [comment] 2017-06-02 13:02
Actually, thinking about it, wouldn't this trigger an update to the ingress? An update appears to trigger `provider.Process()`  at https://github.com/jetstack/kube-lego/blob/master/pkg/provider/gce/gce.go#L102 – which in turn saves the Ingress object.

If that causes the resource version to increment that causes another update event.

In the `UpdateFunc` at https://github.com/jetstack/kube-lego/blob/master/pkg/kubelego/watch.go#L84 it seems there is the intention to check if the data has actually changed with `reflect.DeepEqual`, but of course this fails to account for the resource version. 

Could this cause `kube-lego` to trigger infinite events to itself?

**Comment by ahmetb** [comment] 2017-06-02 16:25
I hit the same issue. (#198)

**Comment by munnerz** [comment] 2017-06-02 16:56
@rolftimmermans I think you're correct here - we need to strip away fields we aren't interested in before performing the `reflect.DeepEqual` check.

With regards to the GCE API, I am unsure. kube-lego itself never directly talks to any Google APIs (only k8s & letsencrypt). My theory would be that each time kube-lego is updating the resource version, the GCLB is *also* performing a reflect.DeepEqual and re-verifying the certificate. I'll need to dig through the GCLB source to assert this first though.

**Comment by munnerz** [comment] 2017-06-02 16:58
So upon a really quick glance, it seems that the same heuristic (simple reflect.DeepEqual) is applied: https://github.com/kubernetes/ingress/blob/master/core/pkg/ingress/controller/controller.go#L190

I'm not certain if GCLB checks the certificates validity/makes any API calls as a result of each update, but it's definitely triggering an update whenever *anything* changes.

**Comment by bvoss** [comment] 2017-06-09 14:54
I just added a quickfix to break up this loop

This just ignores the resource version for the deepEqual and might need some improvement

**Comment by yudilevi** [comment] 2017-06-09 15:10
Ok, great!
Gonna wait for 0.15 before deploying.

**Comment by bvoss** [comment] 2017-06-09 15:22
To be clear is just a [PR 204](https://github.com/jetstack/kube-lego/issues/204) yet and needs to be approved and merged

**Comment by yudilevi** [comment] 2017-06-09 15:24
Sure, and thanks! :)

**Comment by munnerz** [comment] 2017-06-15 08:52
I've merged @bvoss's PR #204 - I'm going to close this issue for now, but if anyone continues to experience problems when running the master build of kube-lego, please re-open!

**Closed by munnerz** 2017-06-15 08:52 UTC

**Comment by yudilevi** [comment] 2017-06-15 09:44
Thanks - will do!

**Comment by munnerz** [comment] 2017-07-03 14:50
I've just cut a release for 0.1.5 that includes this fix!

**Comment by yudilevi** [comment] 2017-07-03 15:31
Great! Thanks!
